import type { NextPage } from 'next';
import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

// app is treated like a node_module
import { QueryPayload } from '@apps/server-app/server';

// How to import sub-modules usually. HOWEVER, this module was not made for a NextJS app so I am not using it
// import DarkMode from '../components/react-dark-mode/src/DarkMode';

const Home: NextPage = () => {
  const [foo, setFoo] = useState('');
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <button
            onClick={() => {
              if (!foo) {
                fetch('http://localhost:4000/data')
                  .then((res) => res.json())
                  .then((data: QueryPayload) => setFoo(data.foo));
              } else {
                setFoo('');
              }
            }}
            className={styles.card}
          >
            {!!foo ? <p>Erase data</p> : <p>Get data from server-app</p>}
            <span>
              Received data:<h2> {foo}</h2>
            </span>
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
